import { Router } from 'express';
import { requireAdmin, requireAuth } from './auth';
import { CommercialBillingService, type BillingCurrency, type BillableUsage, type CommercialPrice, type SubscriptionStatus } from './commercialBilling';

export const createCommercialBillingRouter = (service: CommercialBillingService): Router => {
  const router = Router();
  router.get('/prices', requireAuth, async (_req, res) => res.json(await service.listPrices()));
  router.get('/accounts', requireAuth, async (req, res) => res.json(await service.listAccounts(req.authUser!.userId)));
  router.post('/accounts', requireAuth, async (req, res) => { if (!['USD', 'EUR', 'GBP'].includes(req.body?.currency)) return res.status(400).json({ message: 'Supported billing currency is required' }); return res.status(201).json(await service.createAccount(req.authUser!.userId, req.body.currency as BillingCurrency)); });
  router.post('/accounts/:accountId/checkout', requireAuth, async (req, res) => { if (typeof req.body?.priceId !== 'string' || typeof req.body?.successUrl !== 'string' || typeof req.body?.cancelUrl !== 'string' || typeof req.body?.idempotencyKey !== 'string') return res.status(400).json({ message: 'Checkout parameters are required' }); try { return res.status(201).json(await service.createCheckout(req.params.accountId, req.authUser!.userId, req.body.priceId, { successUrl: req.body.successUrl, cancelUrl: req.body.cancelUrl }, req.body.idempotencyKey)); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.post('/accounts/:accountId/portal', requireAuth, async (req, res) => { try { return res.status(201).json(await service.createPortal(req.params.accountId, req.authUser!.userId, String(req.body?.returnUrl || ''))); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.get('/accounts/:accountId/invoices', requireAuth, async (req, res) => { try { return res.json(await service.listInvoices(req.params.accountId, req.authUser!.userId)); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.get('/accounts/:accountId/overview', requireAuth, async (req, res) => { try { return res.json(await service.billingOverview(req.params.accountId, req.authUser!.userId, String(req.query.period || new Date().toISOString().slice(0, 7)))); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.get('/accounts/:accountId/statements/:period.csv', requireAuth, async (req, res) => { try { const statement = await service.usageStatement(req.params.accountId, req.authUser!.userId, req.params.period); res.setHeader('content-type', 'text/csv; charset=utf-8'); res.setHeader('content-disposition', `attachment; filename="usage-${req.params.period}.csv"`); return res.send(statement); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.post('/subscriptions/:subscriptionId/plan-change', requireAuth, async (req, res) => { try { const subscription = await service.getSubscription(req.params.subscriptionId); await service.assertOwner(subscription.accountId, req.authUser!.userId); return res.json(await service.schedulePlanChange(subscription.subscriptionId, String(req.body?.priceId || ''))); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.post('/subscriptions/:subscriptionId/cancel', requireAuth, async (req, res) => { try { const subscription = await service.getSubscription(req.params.subscriptionId); await service.assertOwner(subscription.accountId, req.authUser!.userId); return res.json(await service.scheduleCancellation(subscription.subscriptionId)); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.post('/prices', requireAdmin, async (req, res) => { try { return res.status(201).json(await service.registerPrice(req.body as CommercialPrice)); } catch (error) { return res.status(400).json({ message: (error as Error).message }); } });
  router.post('/subscriptions', requireAdmin, async (req, res) => { try { return res.status(201).json(await service.startSubscription({ accountId: String(req.body?.accountId || ''), product: req.body?.product, priceId: String(req.body?.priceId || ''), providerSubscriptionId: typeof req.body?.providerSubscriptionId === 'string' ? req.body.providerSubscriptionId : undefined, trialDays: Number.isSafeInteger(req.body?.trialDays) ? req.body.trialDays : undefined })); } catch (error) { return res.status(400).json({ message: (error as Error).message }); } });
  router.post('/subscriptions/:subscriptionId/delinquency', requireAdmin, async (req, res) => { try { return res.json(await service.transitionDelinquency(req.params.subscriptionId, req.body?.status as SubscriptionStatus, String(req.body?.reason || ''))); } catch (error) { return res.status(409).json({ message: (error as Error).message }); } });
  router.post('/subscriptions/:subscriptionId/renew', requireAdmin, async (req, res) => { try { return res.json(await service.renewSubscription(req.params.subscriptionId)); } catch (error) { return res.status(409).json({ message: (error as Error).message }); } });
  router.post('/subscriptions/:subscriptionId/period-close', requireAdmin, async (req, res) => { try { return res.status(201).json(await service.closePeriod({ subscriptionId: req.params.subscriptionId, usage: Array.isArray(req.body?.usage) ? req.body.usage as BillableUsage[] : [], taxMinor: req.body?.taxMinor, discountMinor: req.body?.discountMinor, creditMinor: req.body?.creditMinor, lateUsageGraceHours: req.body?.lateUsageGraceHours })); } catch (error) { return res.status(409).json({ message: (error as Error).message }); } });
  router.post('/invoices/:invoiceId/finalize', requireAdmin, async (req, res) => { try { return res.json(await service.finalizeInvoice(req.params.invoiceId)); } catch (error) { return res.status(409).json({ message: (error as Error).message }); } });
  router.post('/invoices/:invoiceId/reconcile', requireAdmin, async (req, res) => { try { return res.json(await service.reconcile(req.params.invoiceId, Array.isArray(req.body?.usage) ? req.body.usage : [])); } catch (error) { return res.status(404).json({ message: (error as Error).message }); } });
  router.post('/invoices/:invoiceId/corrections', requireAdmin, async (req, res) => { try { return res.json(await service.addCorrection(req.params.invoiceId, { sourceId: String(req.body?.sourceId || ''), amountMinor: Number(req.body?.amountMinor), reason: String(req.body?.reason || '') })); } catch (error) { return res.status(409).json({ message: (error as Error).message }); } });
  router.post('/usage-rollups', requireAdmin, async (req, res) => { try { return res.status(201).json(await service.putUsageRollup(req.body)); } catch (error) { return res.status(400).json({ message: (error as Error).message }); } });
  router.get('/operator/queue', requireAdmin, async (_req, res) => res.json(await service.operatorQueue()));
  return router;
};
