import type { DynamoDBStreamEvent, DynamoDBBatchResponse } from 'aws-lambda';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, TransactWriteCommand } from '@aws-sdk/lib-dynamodb';
import { unmarshall } from '@aws-sdk/util-dynamodb';
import { processingAccountPeriodKey } from './regionalBilling';

export interface BillingRollupDelta { accountId: string; period: string; product: string; spaceId: string; grantedCredits: number; consumedCredits: number; reservedCredits: number; pendingCredits: number; refundedCredits: number; expiredCredits: number; estimatedProviderCostUsd: number; meteredCreditUnits: number; }
const empty = (item: Record<string, any>): BillingRollupDelta => ({ accountId: String(item.accountId), period: String(item.period), product: String(item.product || 'all'), spaceId: String(item.spaceId || 'all'), grantedCredits: 0, consumedCredits: 0, reservedCredits: 0, pendingCredits: 0, refundedCredits: 0, expiredCredits: 0, estimatedProviderCostUsd: 0, meteredCreditUnits: 0 });
export const billingRollupDelta = (oldItem: Record<string, any> | undefined, newItem: Record<string, any> | undefined): BillingRollupDelta | null => { const item = newItem || oldItem; if (!item?.accountId || !item?.period) return null; const delta = empty(item); const units = Number(item.creditUnits || 0); if (!oldItem && item.recordType === 'PROCESSING_CREDIT_GRANT') delta.grantedCredits = units; else if (!oldItem && item.recordType === 'PROCESSING_CREDIT_REFUND') delta.refundedCredits = units; else if (!oldItem && item.recordType === 'PROCESSING_CREDIT_EXPIRATION') delta.expiredCredits = units; else if (item.recordType === 'PROCESSING_CREDIT_RESERVATION') { if (!oldItem && item.state === 'RESERVED') { delta.reservedCredits = units; delta.pendingCredits = units; } else if (oldItem?.state === 'RESERVED' && item.state !== 'RESERVED') { delta.reservedCredits = -units; delta.pendingCredits = -units; } else return null; } else if (!oldItem && item.recordType === 'MEDIA_PROCESSING_USAGE') { delta.consumedCredits = units; delta.meteredCreditUnits = units; delta.estimatedProviderCostUsd = Number(item.estimatedProviderCost || 0); } else return null; return delta; };
const emitMetrics = (delta: BillingRollupDelta) => console.log(JSON.stringify({ _aws: { Timestamp: Date.now(), CloudWatchMetrics: [{ Namespace: 'Gallery/Billing', Dimensions: [['Region'], ['Product', 'Region']], Metrics: [{ Name: 'MeteredCreditUnits', Unit: 'Count' }, { Name: 'ReservedCreditUnits', Unit: 'Count' }, { Name: 'EstimatedProviderCostUsd', Unit: 'None' }] }] }, Product: delta.product, Region: process.env.DATA_HOME_REGION || 'unknown', MeteredCreditUnits: delta.meteredCreditUnits, ReservedCreditUnits: Math.max(0, delta.reservedCredits), EstimatedProviderCostUsd: delta.estimatedProviderCostUsd }));
const emitBalanceMetrics = (item: Record<string, any>) => { const available = Number(item.grantedCreditUnits || 0) + Number(item.refundedCreditUnits || 0) - Number(item.expiredCreditUnits || 0) - Number(item.reservedCreditUnits || 0) - Number(item.consumedCreditUnits || 0); console.log(JSON.stringify({ _aws: { Timestamp: Date.now(), CloudWatchMetrics: [{ Namespace: 'Gallery/Billing', Dimensions: [['Region']], Metrics: [{ Name: 'AvailableCreditBalance', Unit: 'Count' }, { Name: 'NegativeCreditBalance', Unit: 'Count' }] }] }, Region: process.env.DATA_HOME_REGION || 'unknown', AvailableCreditBalance: available, NegativeCreditBalance: available < 0 && item.overagePermitted !== true ? 1 : 0 })); };
export const createRegionalBillingRollupHandler = (client: DynamoDBDocumentClient, tableName: string) => async (event: DynamoDBStreamEvent): Promise<DynamoDBBatchResponse> => { const failures: Array<{ itemIdentifier: string }> = []; for (const record of event.Records) { const eventId = `ROLLUP_EVENT#${record.eventID}`; try { const oldItem = record.dynamodb?.OldImage ? unmarshall(record.dynamodb.OldImage as any) : undefined; const newItem = record.dynamodb?.NewImage ? unmarshall(record.dynamodb.NewImage as any) : undefined; if (newItem?.PK?.startsWith('BALANCE#')) { emitBalanceMetrics(newItem); continue; } const delta = billingRollupDelta(oldItem, newItem); if (!delta) continue; const rollupId = `ROLLUP#${delta.accountId}#${delta.period}#${delta.product}#${delta.spaceId}`; const now = new Date().toISOString(); await client.send(new TransactWriteCommand({ TransactItems: [{ Put: { TableName: tableName, Item: { PK: eventId, recordType: 'BILLING_ROLLUP_EVENT', createdAt: now }, ConditionExpression: 'attribute_not_exists(PK)' } }, { Update: { TableName: tableName, Key: { PK: rollupId }, UpdateExpression: 'SET recordType = :type, accountId = :accountId, period = :period, product = :product, spaceId = :spaceId, GSI1PK = :gsiPk, GSI1SK = :gsiSk, updatedAt = :now ADD grantedCredits :granted, consumedCredits :consumed, reservedCredits :reserved, pendingCredits :pending, refundedCredits :refunded, expiredCredits :expired, estimatedProviderCostUsd :cost', ExpressionAttributeValues: { ':type': 'BILLING_USAGE_ROLLUP', ':accountId': delta.accountId, ':period': delta.period, ':product': delta.product, ':spaceId': delta.spaceId, ':gsiPk': processingAccountPeriodKey(delta.accountId, delta.period), ':gsiSk': `ROLLUP#${delta.product}#${delta.spaceId}`, ':now': now, ':granted': delta.grantedCredits, ':consumed': delta.consumedCredits, ':reserved': delta.reservedCredits, ':pending': delta.pendingCredits, ':refunded': delta.refundedCredits, ':expired': delta.expiredCredits, ':cost': delta.estimatedProviderCostUsd } } }] })); emitMetrics(delta); } catch (error) { if (error instanceof Error && error.name === 'TransactionCanceledException') { const duplicate = await client.send(new GetCommand({ TableName: tableName, Key: { PK: eventId }, ConsistentRead: true })); if (duplicate.Item?.recordType === 'BILLING_ROLLUP_EVENT') continue; } failures.push({ itemIdentifier: record.eventID || 'unknown' }); } } return { batchItemFailures: failures }; };
export const handler = async (event: DynamoDBStreamEvent): Promise<DynamoDBBatchResponse> => createRegionalBillingRollupHandler(DynamoDBDocumentClient.from(new DynamoDBClient({ region: process.env.DATA_HOME_REGION })), process.env.BILLING_LEDGER_TABLE || '')(event);
