import { createHmac, timingSafeEqual } from 'node:crypto';
import { emitCommercialBillingMetric, type CommercialInvoice, type PaymentProvider, type PaymentWebhook } from './commercialBilling';

export class StripePaymentProvider implements PaymentProvider {
  constructor(private secretKey: string, private apiBase = 'https://api.stripe.com/v1', private fetcher: typeof fetch = fetch) { if (!secretKey) throw new Error('Stripe secret key is required'); }
  private async post(path: string, values: Record<string, string | number | boolean | undefined>, idempotencyKey?: string): Promise<any> { const body = new URLSearchParams(); for (const [key, value] of Object.entries(values)) if (value !== undefined) body.set(key, String(value)); const response = await this.fetcher(`${this.apiBase}${path}`, { method: 'POST', headers: { authorization: `Bearer ${this.secretKey}`, 'content-type': 'application/x-www-form-urlencoded', ...(idempotencyKey ? { 'idempotency-key': idempotencyKey } : {}) }, body }); const payload = await response.json() as any; if (!response.ok) { emitCommercialBillingMetric('PaymentProviderFailures'); throw new Error(payload.error?.message || `Stripe request failed (${response.status})`); } return payload; }
  async createCustomer(input: { accountId: string; ownerUserId: string; currency: string }) { const value = await this.post('/customers', { 'metadata[account_id]': input.accountId, 'metadata[owner_user_id]': input.ownerUserId, 'metadata[currency]': input.currency }, `customer-${input.accountId}`); return { customerId: String(value.id) }; }
  async createCheckout(input: { customerId: string; priceId: string; successUrl: string; cancelUrl: string; idempotencyKey: string }) { const value = await this.post('/checkout/sessions', { customer: input.customerId, mode: 'subscription', 'line_items[0][price]': input.priceId, 'line_items[0][quantity]': 1, success_url: input.successUrl, cancel_url: input.cancelUrl, allow_promotion_codes: true, 'automatic_tax[enabled]': true }, input.idempotencyKey); return { sessionId: String(value.id), url: String(value.url) }; }
  async createCustomerPortal(input: { customerId: string; returnUrl: string }) { const value = await this.post('/billing_portal/sessions', { customer: input.customerId, return_url: input.returnUrl }); return { url: String(value.url) }; }
  async createInvoice(invoice: CommercialInvoice & { providerCustomerId: string }, idempotencyKey: string) { for (const line of invoice.lines.filter((item) => item.amountMinor !== 0)) await this.post('/invoiceitems', { customer: invoice.providerCustomerId, currency: invoice.currency.toLowerCase(), amount: line.amountMinor, description: line.description, 'metadata[line_id]': line.lineId, 'metadata[invoice_id]': invoice.invoiceId }, `${idempotencyKey}-${line.lineId}`); const value = await this.post('/invoices', { customer: invoice.providerCustomerId, auto_advance: true, 'metadata[invoice_id]': invoice.invoiceId, description: `${invoice.periodStart} – ${invoice.periodEnd}` }, idempotencyKey); return { providerInvoiceId: String(value.id) }; }
}

/** Verifies Stripe's timestamped `Stripe-Signature` header before normalizing the event. */
export const verifyStripeWebhook = (rawBody: string, signature: string, secret: string, now = new Date(), toleranceSeconds = 300): PaymentWebhook => {
  const values = signature.split(',').reduce<Record<string, string[]>>((all, item) => { const [key, value] = item.split('=', 2); (all[key] ||= []).push(value); return all; }, {}); const timestamp = Number(values.t?.[0]);
  if (!Number.isSafeInteger(timestamp) || Math.abs(Math.floor(now.getTime() / 1000) - timestamp) > toleranceSeconds) throw new Error('Invalid or expired Stripe webhook signature'); const expected = createHmac('sha256', secret).update(`${timestamp}.${rawBody}`).digest(); const valid = (values.v1 || []).some((value) => { if (!/^[a-f0-9]{64}$/i.test(value)) return false; const supplied = Buffer.from(value, 'hex'); return supplied.length === expected.length && timingSafeEqual(supplied, expected); }); if (!valid) throw new Error('Invalid or expired Stripe webhook signature');
  const event = JSON.parse(rawBody) as any; if (!event.id || !event.type || !event.data?.object) throw new Error('Stripe webhook is incomplete'); const object = event.data.object; const type = event.type === 'customer.subscription.deleted' ? 'subscription.canceled' : String(event.type); return { eventId: String(event.id), type, createdAt: new Date(Number(event.created || timestamp) * 1000).toISOString(), data: { subscriptionId: String(object.metadata?.subscription_id || object.subscription_details?.metadata?.subscription_id || object.subscription || object.id || ''), invoiceId: String(object.metadata?.invoice_id || ''), providerInvoiceId: object.object === 'invoice' ? String(object.id) : undefined, providerCustomerId: String(object.customer || '') } };
};
