import { createHmac } from 'node:crypto';
import { CommercialBillingService, InMemoryCommercialBillingRepository, verifyPaymentWebhook, type PaymentProvider } from '../src/commercialBilling';

const provider = (): jest.Mocked<PaymentProvider> => ({ createCustomer: jest.fn().mockResolvedValue({ customerId: 'cus_1' }), createCheckout: jest.fn().mockResolvedValue({ sessionId: 'checkout_1', url: 'https://pay.example/checkout' }), createCustomerPortal: jest.fn().mockResolvedValue({ url: 'https://pay.example/portal' }), createInvoice: jest.fn().mockResolvedValue({ providerInvoiceId: 'invoice_provider_1' }) });
const price = { priceId: 'price-pro-monthly-v1', product: 'eversally' as const, name: 'Pro', version: '2026-08-25', currency: 'USD' as const, interval: 'month' as const, unitAmountMinor: 2000, includedProcessingCredits: 100, overageUnitAmountMinor: 5, taxBehavior: 'EXCLUSIVE' as const, active: true };

describe('commercial billing lifecycle', () => {
  let repository: InMemoryCommercialBillingRepository; let gateway: jest.Mocked<PaymentProvider>; let service: CommercialBillingService;
  beforeEach(() => { repository = new InMemoryCommercialBillingRepository(); gateway = provider(); service = new CommercialBillingService(repository, gateway, () => new Date('2026-08-25T00:00:00.000Z')); });

  const setup = async (trialDays?: number) => { await service.registerPrice(price); const account = await service.createAccount('owner', 'USD'); const subscription = await service.startSubscription({ accountId: account.accountId, product: 'eversally', priceId: price.priceId, trialDays }); return { account, subscription }; };

  it('models account ownership, trials, plan changes, cancellation, and product entitlement', async () => { const { account, subscription } = await setup(14); expect(subscription.status).toBe('TRIALING'); expect(await service.entitlement(account.accountId, 'eversally')).toMatchObject({ allowed: true, includedProcessingCredits: 100, overagePermitted: true }); expect(await service.schedulePlanChange(subscription.subscriptionId, price.priceId)).toMatchObject({ scheduledPriceId: price.priceId }); expect(await service.scheduleCancellation(subscription.subscriptionId)).toMatchObject({ cancelAtPeriodEnd: true }); await expect(service.createPortal(account.accountId, 'not-owner', 'https://app.example/billing')).rejects.toThrow('not found'); });
  it('applies scheduled plan changes and cancellation only at renewal', async () => { const { subscription } = await setup(); await service.schedulePlanChange(subscription.subscriptionId, price.priceId); expect(await service.renewSubscription(subscription.subscriptionId)).toMatchObject({ priceVersion: price.version, scheduledPriceId: undefined }); await service.scheduleCancellation(subscription.subscriptionId); expect(await service.renewSubscription(subscription.subscriptionId)).toMatchObject({ status: 'CANCELED', canceledAt: expect.any(String) }); });

  it('integrates hosted checkout and customer portal with idempotency', async () => { const { account } = await setup(); await expect(service.createCheckout(account.accountId, 'owner', price.priceId, { successUrl: 'https://app.example/success', cancelUrl: 'https://app.example/cancel' }, 'checkout-account-1')).resolves.toMatchObject({ sessionId: 'checkout_1' }); expect(gateway.createCheckout).toHaveBeenCalledWith(expect.objectContaining({ customerId: 'cus_1', idempotencyKey: 'checkout-account-1' })); await service.createPortal(account.accountId, 'owner', 'https://app.example/billing'); expect(gateway.createCustomerPortal).toHaveBeenCalled(); });

  it('builds a customer usage read model and downloadable statement by period and space', async () => { const { account } = await setup(); await service.putUsageRollup({ rollupId: 'account:2026-08:space-1', accountId: account.accountId, period: '2026-08', product: 'eversally', spaceId: 'space-1', grantedCredits: 100, consumedCredits: 72, reservedCredits: 8, pendingCredits: 3, estimatedProviderCostMinor: 14, updatedAt: '2026-08-25T00:00:00.000Z' }); const overview = await service.billingOverview(account.accountId, 'owner', '2026-08'); expect(overview.totals).toMatchObject({ availableCredits: 20, consumedCredits: 72, reservedCredits: 8, pendingCredits: 3 }); await expect(service.usageStatement(account.accountId, 'owner', '2026-08')).resolves.toContain('"space-1","100","72","8","3","14"'); });

  it('aggregates included and overage usage into an invoice with tax and discounts', async () => { const { account, subscription } = await setup(); const invoice = await service.closePeriod({ subscriptionId: subscription.subscriptionId, usage: [{ usageId: 'usage-1', accountId: account.accountId, product: 'eversally', occurredAt: '2026-08-26T00:00:00.000Z', creditUnits: 125, estimatedProviderCostMinor: 20, priceBookVersion: 'v1' }], taxMinor: 200, discountMinor: 100 }); expect(invoice).toMatchObject({ subtotalMinor: 2125, taxMinor: 200, discountMinor: 100, totalMinor: 2225, status: 'DRAFT' }); expect(invoice.lines.find((line) => line.kind === 'USAGE')).toMatchObject({ quantity: 25, amountMinor: 125, sourceIds: ['usage-1'] }); expect(await service.finalizeInvoice(invoice.invoiceId)).toMatchObject({ status: 'OPEN', providerInvoiceId: 'invoice_provider_1' }); });

  it('accepts late usage only through the explicit grace cutoff and records reconciliation gaps', async () => { const { account, subscription } = await setup(); const invoice = await service.closePeriod({ subscriptionId: subscription.subscriptionId, usage: [], lateUsageGraceHours: 24 }); const issues = await service.reconcile(invoice.invoiceId, [{ usageId: 'late', accountId: account.accountId, product: 'eversally', occurredAt: subscription.currentPeriodEnd, creditUnits: 1, estimatedProviderCostMinor: 0, priceBookVersion: 'v1' }]); expect(issues.map((item) => item.type)).toEqual(['MISSING_USAGE', 'PROVIDER_COST_MISSING']); expect(await service.operatorQueue()).toHaveLength(2); });
  it('records idempotent invoice corrections before finalization', async () => { const { subscription } = await setup(); const invoice = await service.closePeriod({ subscriptionId: subscription.subscriptionId, usage: [] }); const corrected = await service.addCorrection(invoice.invoiceId, { sourceId: 'reconciliation-1', amountMinor: -100, reason: 'Usage correction' }); expect(corrected).toMatchObject({ subtotalMinor: 1900, totalMinor: 1900 }); expect((await service.addCorrection(invoice.invoiceId, { sourceId: 'reconciliation-1', amountMinor: -100, reason: 'Usage correction' })).lines.filter((line) => line.kind === 'CORRECTION')).toHaveLength(1); });

  it('implements payment failure, grace, suspension, recovery, cancellation, and write-off transitions', async () => { const { subscription } = await setup(); expect((await service.transitionDelinquency(subscription.subscriptionId, 'PAST_DUE', 'failed')).status).toBe('PAST_DUE'); expect((await service.transitionDelinquency(subscription.subscriptionId, 'GRACE_PERIOD', 'dunning')).graceEndsAt).toBeDefined(); expect((await service.transitionDelinquency(subscription.subscriptionId, 'SUSPENDED', 'grace expired')).status).toBe('SUSPENDED'); expect((await service.transitionDelinquency(subscription.subscriptionId, 'ACTIVE', 'paid')).status).toBe('ACTIVE'); expect((await service.transitionDelinquency(subscription.subscriptionId, 'CANCELED', 'requested')).status).toBe('CANCELED'); const second = await service.startSubscription({ accountId: subscription.accountId, product: 'eversally', priceId: price.priceId }); await service.transitionDelinquency(second.subscriptionId, 'PAST_DUE', 'failed'); await service.transitionDelinquency(second.subscriptionId, 'SUSPENDED', 'grace expired'); expect((await service.transitionDelinquency(second.subscriptionId, 'WRITTEN_OFF', 'uncollectible')).status).toBe('WRITTEN_OFF'); });

  it('verifies signed webhooks and suppresses event replays', async () => { const { subscription } = await setup(); const event = { eventId: 'evt_1', type: 'invoice.payment_failed', createdAt: '2026-08-25T00:00:00.000Z', data: { subscriptionId: subscription.subscriptionId } }; const raw = JSON.stringify(event), timestamp = 1787616000, secret = 'secret'; const signature = `t=${timestamp},v1=${createHmac('sha256', secret).update(`${timestamp}.${raw}`).digest('hex')}`; const verified = verifyPaymentWebhook(raw, signature, secret, new Date(timestamp * 1000)); await expect(service.applyWebhook(verified)).resolves.toBe(true); await expect(service.applyWebhook(verified)).resolves.toBe(false); expect((await repository.getSubscription(subscription.subscriptionId))?.status).toBe('PAST_DUE'); expect(() => verifyPaymentWebhook(raw, signature.replace(/.$/, '0'), secret, new Date(timestamp * 1000))).toThrow('signature'); });
  it('retries a durable received webhook after an application failure', async () => { const { subscription } = await setup(); const event = { eventId: 'evt_retry', type: 'invoice.payment_failed', createdAt: '2026-08-25T01:00:00.000Z', data: { subscriptionId: subscription.subscriptionId } }; const putSubscription = jest.spyOn(repository, 'putSubscription').mockRejectedValueOnce(new Error('transient write failure')); await expect(service.applyWebhook(event)).rejects.toThrow('transient write failure'); expect(await repository.getWebhook(event.eventId)).toMatchObject({ processingStatus: 'RECEIVED' }); await expect(service.applyWebhook(event)).resolves.toBe(true); expect(putSubscription).toHaveBeenCalledTimes(3); expect(await repository.getWebhook(event.eventId)).toMatchObject({ processingStatus: 'APPLIED' }); });
  it('ignores an older reordered provider event after a newer recovery', async () => { const { subscription } = await setup(); await service.applyWebhook({ eventId: 'new', type: 'invoice.paid', createdAt: '2026-08-25T02:00:00.000Z', data: { subscriptionId: subscription.subscriptionId } }); await expect(service.applyWebhook({ eventId: 'old', type: 'invoice.payment_failed', createdAt: '2026-08-25T01:00:00.000Z', data: { subscriptionId: subscription.subscriptionId } })).resolves.toBe(false); expect((await repository.getSubscription(subscription.subscriptionId))?.status).toBe('ACTIVE'); });
  it('flags actual provider-cost variance during reconciliation', async () => { const { account, subscription } = await setup(); const usage = { usageId: 'usage-cost', accountId: account.accountId, product: 'eversally' as const, occurredAt: '2026-08-26T00:00:00.000Z', creditUnits: 10, estimatedProviderCostMinor: 20, actualProviderCostMinor: 35, priceBookVersion: 'v1' }; const invoice = await service.closePeriod({ subscriptionId: subscription.subscriptionId, usage: [usage] }); expect(await service.reconcile(invoice.invoiceId, [usage])).toEqual([expect.objectContaining({ type: 'AMOUNT_MISMATCH', expectedMinor: 20, actualMinor: 35 })]); });
});
