import type { SQSEvent } from 'aws-lambda';
import sharp from 'sharp';
import { createRegionalImageIngestHandler, type RegionalImageIngestMessage } from '../src/regionalImageIngestHandler';
const message: RegionalImageIngestMessage = { product: 'eversally', environment: 'production', dataHomeRegion: 'us-east-2', assetId: 'a', mediaVersionId: 'v', quarantineBucket: 'quarantine', quarantineObjectKey: 'uploads/image.jpg', mimeType: 'image/jpeg' };
const event = (body: unknown, receiveCount = '1'): SQSEvent => ({ Records: [{ messageId: 'm', body: JSON.stringify(body), attributes: { ApproximateReceiveCount: receiveCount } }] } as SQSEvent);
describe('regional image ingest handler', () => {
  beforeEach(() => Object.assign(process.env, { PRODUCT: 'eversally', ENVIRONMENT: 'production', DATA_HOME_REGION: 'us-east-2', QUARANTINE_BUCKET: 'quarantine' }));
  it('reads only the local quarantine object and persists paired scans', async () => {
    const bytes = await sharp({ create: { width: 2, height: 2, channels: 3, background: '#fff' } }).jpeg().toBuffer(); const persistAndEnqueue = jest.fn().mockResolvedValue(undefined);
    const reserve = jest.fn().mockResolvedValue(undefined); const handler = createRegionalImageIngestHandler({ authorize: jest.fn(), read: jest.fn().mockResolvedValue({ bytes, mimeType: 'image/jpeg' }), reserve, persistAndEnqueue, markUnavailable: jest.fn(), deferRetry: jest.fn() });
    await expect(handler(event(message))).resolves.toEqual({ batchItemFailures: [] });
    expect(persistAndEnqueue.mock.calls[0][1].scanJobs.map(({ type }: any) => type)).toEqual(['IMAGE_MODERATION', 'FACE_AGE']);
    expect(reserve).toHaveBeenCalledWith(message, persistAndEnqueue.mock.calls[0][1]);
    expect(reserve.mock.invocationCallOrder[0]).toBeLessThan(persistAndEnqueue.mock.invocationCallOrder[0]);
  });
  it('derives opaque identifiers from the regional quarantine key notification', async () => { const bytes = await sharp({ create: { width: 2, height: 2, channels: 3, background: '#fff' } }).jpeg().toBuffer(); const persistAndEnqueue = jest.fn().mockResolvedValue(undefined); const handler = createRegionalImageIngestHandler({ authorize: jest.fn(), read: jest.fn().mockResolvedValue({ bytes, mimeType: 'image/jpeg' }), persistAndEnqueue, markUnavailable: jest.fn(), deferRetry: jest.fn() }); const notification = { Records: [{ eventSource: 'aws:s3', s3: { bucket: { name: 'quarantine' }, object: { key: 'images%2Fasset%2Fversion%2Fsource' } } }] }; await expect(handler(event(notification))).resolves.toEqual({ batchItemFailures: [] }); expect(persistAndEnqueue).toHaveBeenCalledWith(expect.objectContaining({ assetId: 'asset', mediaVersionId: 'version' }), expect.anything()); });
  it('rejects cross-region messages before reading bytes', async () => { const read = jest.fn(); const handler = createRegionalImageIngestHandler({ authorize: jest.fn(), read, persistAndEnqueue: jest.fn(), markUnavailable: jest.fn(), deferRetry: jest.fn() }); await expect(handler(event({ ...message, dataHomeRegion: 'eu-central-1' }))).resolves.toEqual({ batchItemFailures: [{ itemIdentifier: 'm' }] }); expect(read).not.toHaveBeenCalled(); });
  it('rejects an upload not authorized by the regional Asset before reading bytes', async () => { const read = jest.fn(); const authorize = jest.fn().mockRejectedValue(new Error('not authorized')); const handler = createRegionalImageIngestHandler({ authorize, read, persistAndEnqueue: jest.fn(), markUnavailable: jest.fn(), deferRetry: jest.fn() }); await expect(handler(event(message))).resolves.toEqual({ batchItemFailures: [{ itemIdentifier: 'm' }] }); expect(authorize).toHaveBeenCalledWith(message); expect(read).not.toHaveBeenCalled(); });
  it('acknowledges a duplicate event for an already consumed upload', async () => { const read = jest.fn(); const handler = createRegionalImageIngestHandler({ authorize: jest.fn().mockResolvedValue('CONSUMED'), read, persistAndEnqueue: jest.fn(), markUnavailable: jest.fn(), deferRetry: jest.fn() }); await expect(handler(event(message))).resolves.toEqual({ batchItemFailures: [] }); expect(read).not.toHaveBeenCalled(); });
  it('records unavailable instead of silently clearing exhausted ingest work', async () => { const markUnavailable = jest.fn().mockResolvedValue(undefined); const handler = createRegionalImageIngestHandler({ authorize: jest.fn(), read: jest.fn().mockRejectedValue(Object.assign(new Error('missing'), { name: 'NoSuchKey' })), persistAndEnqueue: jest.fn(), markUnavailable, deferRetry: jest.fn() }); await expect(handler(event(message, '5'))).resolves.toEqual({ batchItemFailures: [] }); expect(markUnavailable).toHaveBeenCalledWith(message, 'NoSuchKey'); });
  it('releases reserved credits when exhausted persistence work fails', async () => { const bytes = await sharp({ create: { width: 2, height: 2, channels: 3, background: '#fff' } }).jpeg().toBuffer(); const release = jest.fn().mockResolvedValue(undefined); const handler = createRegionalImageIngestHandler({ authorize: jest.fn(), read: jest.fn().mockResolvedValue({ bytes, mimeType: 'image/jpeg' }), reserve: jest.fn().mockResolvedValue(undefined), release, persistAndEnqueue: jest.fn().mockRejectedValue(Object.assign(new Error('write'), { name: 'PersistenceFailure' })), markUnavailable: jest.fn(), deferRetry: jest.fn() }); await expect(handler(event(message, '5'))).resolves.toEqual({ batchItemFailures: [] }); expect(release).toHaveBeenCalledWith(message, expect.any(String), 'PersistenceFailure'); });
});
