import { TransactWriteCommand } from '@aws-sdk/lib-dynamodb';
import { billingRollupDelta, createRegionalBillingRollupHandler } from '../src/regionalBillingRollupHandler';

describe('regional billing rollup stream', () => {
  const reservation = { recordType: 'PROCESSING_CREDIT_RESERVATION', accountId: 'account', period: '2026-08', product: 'eversally', spaceId: 'space', creditUnits: 25, state: 'RESERVED' };
  it('derives ordered lifecycle deltas without double-counting consumption', () => { expect(billingRollupDelta(undefined, { recordType: 'PROCESSING_CREDIT_GRANT', accountId: 'account', period: '2026-08', creditUnits: 100 })).toMatchObject({ grantedCredits: 100 }); expect(billingRollupDelta(undefined, reservation)).toMatchObject({ reservedCredits: 25, pendingCredits: 25, consumedCredits: 0 }); expect(billingRollupDelta(reservation, { ...reservation, state: 'CONSUMED' })).toMatchObject({ reservedCredits: -25, pendingCredits: -25, consumedCredits: 0 }); expect(billingRollupDelta(undefined, { recordType: 'MEDIA_PROCESSING_USAGE', accountId: 'account', period: '2026-08', product: 'eversally', spaceId: 'space', creditUnits: 25, estimatedProviderCost: 0.02 })).toMatchObject({ consumedCredits: 25, meteredCreditUnits: 25, estimatedProviderCostUsd: 0.02 }); });
  it('writes the rollup and stream-event idempotency marker atomically', async () => { const send = jest.fn().mockResolvedValue({}); const handler = createRegionalBillingRollupHandler({ send } as any, 'billing'); const image = (value: unknown) => Object.fromEntries(Object.entries(value as any).map(([key, item]) => [key, typeof item === 'number' ? { N: String(item) } : { S: String(item) }])); const event = { Records: [{ eventID: 'event-1', dynamodb: { NewImage: image({ ...reservation, PK: 'RESERVATION#one' }) } }] } as any; await expect(handler(event)).resolves.toEqual({ batchItemFailures: [] }); const transaction = send.mock.calls[0][0] as TransactWriteCommand; expect(transaction.input.TransactItems).toEqual(expect.arrayContaining([expect.objectContaining({ Put: expect.objectContaining({ Item: expect.objectContaining({ PK: 'ROLLUP_EVENT#event-1' }), ConditionExpression: 'attribute_not_exists(PK)' }) }), expect.objectContaining({ Update: expect.objectContaining({ Key: { PK: 'ROLLUP#account#2026-08#eversally#space' }, UpdateExpression: expect.stringContaining('ADD grantedCredits') }) })])); });
  it('acknowledges a duplicate stream event without applying its delta twice', async () => { const duplicate = Object.assign(new Error('duplicate'), { name: 'TransactionCanceledException' }); const send = jest.fn().mockRejectedValueOnce(duplicate).mockResolvedValueOnce({ Item: { PK: 'ROLLUP_EVENT#event-1', recordType: 'BILLING_ROLLUP_EVENT' } }); const handler = createRegionalBillingRollupHandler({ send } as any, 'billing'); const event = { Records: [{ eventID: 'event-1', dynamodb: { NewImage: { PK: { S: 'USAGE#one' }, recordType: { S: 'MEDIA_PROCESSING_USAGE' }, accountId: { S: 'account' }, period: { S: '2026-08' }, product: { S: 'eversally' }, spaceId: { S: 'space' }, creditUnits: { N: '1' } } } }] } as any; await expect(handler(event)).resolves.toEqual({ batchItemFailures: [] }); });
  it('retries a canceled transaction when no idempotency marker exists', async () => { const canceled = Object.assign(new Error('capacity'), { name: 'TransactionCanceledException' }); const send = jest.fn().mockRejectedValueOnce(canceled).mockResolvedValueOnce({}); const handler = createRegionalBillingRollupHandler({ send } as any, 'billing'); const event = { Records: [{ eventID: 'event-2', dynamodb: { NewImage: { PK: { S: 'USAGE#two' }, recordType: { S: 'MEDIA_PROCESSING_USAGE' }, accountId: { S: 'account' }, period: { S: '2026-08' }, product: { S: 'eversally' }, spaceId: { S: 'space' }, creditUnits: { N: '1' } } } }] } as any; await expect(handler(event)).resolves.toEqual({ batchItemFailures: [{ itemIdentifier: 'event-2' }] }); });
});
