import { useEffect, useMemo, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { api } from '../api';
import type { CurrentUser } from '../cognitoAuth';

type Account = { accountId: string; currency: 'USD' | 'EUR' | 'GBP' };
type Price = { priceId: string; name: string; product: string; currency: string; interval: string; unitAmountMinor: number; includedProcessingCredits: number; overageUnitAmountMinor?: number };
type Usage = { rollupId: string; product: string; spaceId: string; grantedCredits: number; consumedCredits: number; reservedCredits: number; pendingCredits: number; estimatedProviderCostMinor: number };
type Invoice = { invoiceId: string; status: string; totalMinor: number; currency: string; periodStart: string; periodEnd: string; providerInvoiceId?: string };
type Overview = { account: Account; subscription: { status: string; currentPeriodEnd: string } | null; price: Price | null; period: string; totals: { grantedCredits: number; consumedCredits: number; reservedCredits: number; pendingCredits: number; availableCredits: number }; usage: Usage[]; invoices: Invoice[] };

const money = (minor: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(minor / 100);
const month = () => new Date().toISOString().slice(0, 7);

export default function BillingPage({ user }: { user: CurrentUser | null }) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [prices, setPrices] = useState<Price[]>([]); const [overview, setOverview] = useState<Overview | null>(null); const [period, setPeriod] = useState(month()); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async (selectedPeriod = period) => { setLoading(true); setError(''); try { const [loadedAccounts, loadedPrices] = await Promise.all([api.billingAccounts() as Promise<Account[]>, api.billingPrices() as Promise<Price[]>]); setAccounts(loadedAccounts); setPrices(loadedPrices); setOverview(loadedAccounts[0] ? await api.billingOverview(loadedAccounts[0].accountId, selectedPeriod) as Overview : null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Billing is temporarily unavailable.'); } finally { setLoading(false); } };
  useEffect(() => { if (user) void load(); }, [user?.username]);
  const capacity = overview?.totals.grantedCredits || overview?.price?.includedProcessingCredits || 0; const used = (overview?.totals.consumedCredits || 0) + (overview?.totals.reservedCredits || 0); const usagePercent = capacity ? Math.min(100, Math.round((used / capacity) * 100)) : 0; const exhausted = Boolean(overview && overview.totals.availableCredits <= 0); const warning = usagePercent >= 80;
  const upgrade = useMemo(() => prices.find((item) => item.priceId !== overview?.price?.priceId) || prices[0], [prices, overview?.price?.priceId]);
  if (!user) return <Navigate to="/auth/signin" replace />;
  const createAccount = async () => { setBusy('account'); try { await api.createBillingAccount('USD'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create billing account.'); } finally { setBusy(''); } };
  const openPortal = async () => { if (!overview) return; setBusy('portal'); try { const result = await api.createBillingPortal(overview.account.accountId) as { url: string }; window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not open payment settings.'); } finally { setBusy(''); } };
  const openCheckout = async () => { if (!overview || !upgrade) return; setBusy('checkout'); try { const result = await api.createBillingCheckout(overview.account.accountId, upgrade.priceId) as { url: string }; window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not start checkout.'); } finally { setBusy(''); } };
  return <main className="billing-page">
    <header className="billing-hero"><div><span className="billing-eyebrow">Account</span><h1>Billing & usage</h1><p>See processing credits, current plan, invoices, and payment settings in one place.</p></div>{overview && <button className="billing-button secondary" onClick={() => void openPortal()} disabled={Boolean(busy)}>{busy === 'portal' ? 'Opening…' : 'Manage payment methods'}</button>}</header>
    {error && <div className="billing-alert danger"><strong>Billing could not load.</strong><span>{error}</span><button onClick={() => void load()}>Try again</button></div>}
    {loading ? <div className="billing-loading">Loading billing details…</div> : !accounts.length ? <section className="billing-empty"><div className="billing-empty-icon">◎</div><h2>Set up billing</h2><p>Create your billing profile to choose a plan and receive processing credits.</p><button className="billing-button" onClick={() => void createAccount()} disabled={busy === 'account'}>{busy ? 'Creating…' : 'Get started'}</button></section> : overview && <>
      {exhausted && <div className="billing-alert danger"><div><strong>Processing credits exhausted</strong><span>New processing and delivery are paused. Upgrade or update your payment settings to continue.</span></div><button className="billing-button" onClick={() => void openCheckout()}>Upgrade now</button></div>}
      {!exhausted && warning && <div className="billing-alert warning"><div><strong>You’ve used {usagePercent}% of this month’s credits</strong><span>Upgrade now to avoid interrupted processing.</span></div><button onClick={() => void openCheckout()}>View plans</button></div>}
      <section className="billing-summary-grid"><article className="billing-card plan"><span className="billing-card-label">Current plan</span><div className="billing-plan-name">{overview.price?.name || 'No active plan'} <span>{overview.subscription?.status?.replace('_', ' ').toLowerCase() || 'inactive'}</span></div><p>{overview.price ? `${money(overview.price.unitAmountMinor, overview.price.currency)} / ${overview.price.interval}` : 'Choose a plan to enable processing.'}</p><div className="billing-card-actions"><button className="billing-button" onClick={() => void openCheckout()} disabled={!upgrade || Boolean(busy)}>{overview.price ? 'Change plan' : 'Choose a plan'}</button><button className="billing-link-button" onClick={() => void openPortal()}>Payment settings</button></div></article>
      <article className="billing-card credits"><div className="billing-card-heading"><span className="billing-card-label">Processing credits</span><strong>{Math.max(0, overview.totals.availableCredits).toLocaleString()} available</strong></div><div className="billing-progress" role="progressbar" aria-valuenow={usagePercent} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${usagePercent}%` }} /></div><div className="billing-credit-legend"><span><i className="used" />{overview.totals.consumedCredits.toLocaleString()} used</span><span><i className="reserved" />{overview.totals.reservedCredits.toLocaleString()} reserved</span><span>{capacity.toLocaleString()} total</span></div><small>{overview.totals.pendingCredits ? `${overview.totals.pendingCredits} credits pending final usage.` : 'Usage updates as processing completes.'}</small></article></section>
      <section className="billing-section"><div className="billing-section-heading"><div><span className="billing-eyebrow">Usage detail</span><h2>Credits by space</h2></div><div className="billing-period-actions"><input type="month" value={period} onChange={(event) => { setPeriod(event.target.value); void load(event.target.value); }} /><button className="billing-download" onClick={() => void api.downloadBillingStatement(overview.account.accountId, period)}>Download CSV</button></div></div><div className="billing-table-wrap"><table className="billing-table"><thead><tr><th>Space</th><th>Product</th><th>Used</th><th>Reserved</th><th>Pending</th></tr></thead><tbody>{overview.usage.length ? overview.usage.map((item) => <tr key={item.rollupId}><td>{item.spaceId}</td><td><span className="billing-product-pill">{item.product}</span></td><td>{item.consumedCredits.toLocaleString()}</td><td>{item.reservedCredits.toLocaleString()}</td><td>{item.pendingCredits.toLocaleString()}</td></tr>) : <tr><td colSpan={5} className="billing-table-empty">No usage recorded for this period.</td></tr>}</tbody></table></div></section>
      <section className="billing-section"><div className="billing-section-heading"><div><span className="billing-eyebrow">History</span><h2>Invoices</h2></div><button className="billing-link-button" onClick={() => void openPortal()}>View all in portal</button></div><div className="billing-invoices">{overview.invoices.length ? overview.invoices.slice(0, 6).map((invoice) => <article key={invoice.invoiceId}><div><strong>{new Date(invoice.periodStart).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</strong><span>{new Date(invoice.periodStart).toLocaleDateString()} – {new Date(invoice.periodEnd).toLocaleDateString()}</span></div><span className={`billing-status ${invoice.status.toLowerCase()}`}>{invoice.status.toLowerCase()}</span><strong>{money(invoice.totalMinor, invoice.currency)}</strong><button onClick={() => void openPortal()} aria-label="Open invoice">↗</button></article>) : <p className="billing-muted">Invoices will appear here after your first billing period.</p>}</div></section>
    </>}
  </main>;
}
